### ISSUE TITLE
When laravel 7 ?

### ISSUE THREAD

**Issue by sascha1337** [rafaellaurindo/laravel-telegram-logging#2]

**Comment by rafaellaurindo** [comment]
Hi, @sascha1337, I just added support for Laravel 7. *. :rocket:

Thank you!

**Comment by sascha1337** [comment]
Yay! Thank you so much, really helpful, thanks for the fast response and update !

**Comment by rafaellaurindo** [comment]
Perfect! I am grateful to be able to help!😉
