### ISSUE TITLE
Composer - Deprecation Notice

### ISSUE THREAD

**Issue by Claud** [rafaellaurindo/laravel-telegram-logging#4]
`Deprecation Notice: Class RLaurindo\TelegramLogger\TelegramService located in ./vendor/rafaellaurindo/laravel-telegram-logging/src/Services/TelegramService.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201
`

**Comment by rafaellaurindo** [comment]
Fixed in this new version.

**Comment by Claud** [comment]
```
Class RLaurindo\TelegramLogger\TelegramService located in /vendor/rafaellaurindo/laravel-telegram-logging/src\Services\TelegramService.php does not c
omply with psr-4 autoloading standard. Skipping.
```
The fix didn't help. :{
