### ISSUE TITLE
TelegramService.php does not comply with psr-4 autoloading standard. Skipping.

### ISSUE THREAD

**Issue by joemags-apps** [rafaellaurindo/laravel-telegram-logging#8]
Class RLaurindo\TelegramLogger\TelegramService located in ./vendor/rafaellaurindo/laravel-telegram-logging/src/Services/TelegramService.php does not comply with psr-4 autoloading standard. Skipping.
![image](https://user-images.githubusercontent.com/63977646/104563456-564b1400-5652-11eb-9290-962da2dfbad3.png)

**Comment by joemags-apps** [comment]
Unable to create configured logger. Using emergency logger. {"exception":"[object] (Error(code: 0): Class 'RLaurindo\\TelegramLogger\\TelegramService' not found at /home/.../vendor/rafaellaurindo/laravel-telegram-logging/src/TelegramLoggerHandler.php:50)

**Comment by rafaellaurindo** [comment]
Hello @joemags-apps, this error has been resolved in the current version. 🚀
